Objs  			= FrontEndDescription.o BeBoard.o Cbc.o Module.o 
CC              = g++
CXX             = g++
CCFlags         = -g -O1 -Wall -fPIC -pedantic

IncludeDirs     =
IncludePaths            = $(IncludeDirs:%=-I%)

.PHONY: clean print

%.o: %.cc %.h
	$(CXX) -std=c++11 $(CCFlags) $(IncludePaths) -c -o $@ $<


all: print $(Objs)
	$(CC) -shared -o libPh2_Description.so $(Objs)
	mv libPh2_Description.so ../lib

print:
	@echo '****************************'
	@echo 'Building HWDescription objects'
	@echo '****************************'
clean:
	rm -f *.o
